version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: metal_against_demons
      POSTGRES_USER: metal_against_demons
      POSTGRES_PASSWORD: metal_against_demons
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: